"""
Document generation utilities for output files
"""
import uuid
import os
from datetime import datetime
from docx import Document
from openpyxl import Workbook
from app.utils.file_storage import save_generated_document


async def generate_docx_file(text: str, conversation_id: str = None, title: str = ""):
    """Generate DOCX file from text content and save locally"""
    doc = Document()
    doc.add_paragraph(text)
    
    # Generate unique filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_hash = uuid.uuid4().hex[:8]
    
    # Create safe filename
    safe_title = "".join(c for c in title[:30] if c.isalnum() or c in (' ', '-', '_')).rstrip()
    safe_title = safe_title.replace(' ', '_') if safe_title else "document"
    
    filename = f"{conversation_id or 'default'}_{timestamp}_{safe_title}_{file_hash}.docx"
    
    # Generate document content
    from io import BytesIO
    buffer = BytesIO()
    doc.save(buffer)
    content = buffer.getvalue()
    
    # Save locally using file storage system
    local_file_path = await save_generated_document(
        content=content,
        conversation_id=conversation_id or "default",
        file_type="docx",
        title=title or "Generated Document"
    )
    
    return {"file": local_file_path}


async def generate_xlsx_file(text: str, conversation_id: str = None, title: str = ""):
    """Generate XLSX file from text content and save locally"""
    wb = Workbook()
    ws = wb.active
    ws.title = "Data"
    ws.append(["Prompt", "Response"])
    ws.append([text, "Generated by AI"])
    
    # Generate unique filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_hash = uuid.uuid4().hex[:8]
    
    # Create safe filename
    safe_title = "".join(c for c in title[:30] if c.isalnum() or c in (' ', '-', '_')).rstrip()
    safe_title = safe_title.replace(' ', '_') if safe_title else "spreadsheet"
    
    filename = f"{conversation_id or 'default'}_{timestamp}_{safe_title}_{file_hash}.xlsx"
    
    # Generate spreadsheet content
    from io import BytesIO
    buffer = BytesIO()
    wb.save(buffer)
    content = buffer.getvalue()
    
    # Save locally using file storage system
    local_file_path = await save_generated_document(
        content=content,
        conversation_id=conversation_id or "default",
        file_type="xlsx",
        title=title or "Generated Spreadsheet"
    )
    
    return {"file": local_file_path}
